[2025-03-19T15:36:43.645+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-19T15:36:43.685+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pyspark_etl_pipeline.gold_ingestion manual__2025-03-19T05:14:09.222928+00:00 [queued]>
[2025-03-19T15:36:43.706+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pyspark_etl_pipeline.gold_ingestion manual__2025-03-19T05:14:09.222928+00:00 [queued]>
[2025-03-19T15:36:43.707+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-19T15:36:43.728+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): gold_ingestion> on 2025-03-19 05:14:09.222928+00:00
[2025-03-19T15:36:43.739+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pyspark_etl_pipeline', 'gold_ingestion', 'manual__2025-03-19T05:14:09.222928+00:00', '--job-id', '121', '--raw', '--subdir', 'DAGS_FOLDER/dag_pipeline.py', '--cfg-path', '/tmp/tmpfi0pnhv7']
[2025-03-19T15:36:43.744+0000] {standard_task_runner.py:105} INFO - Job 121: Subtask gold_ingestion
[2025-03-19T15:36:43.746+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=362) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-19T15:36:43.749+0000] {standard_task_runner.py:72} INFO - Started process 363 to run task
[2025-03-19T15:36:43.819+0000] {task_command.py:467} INFO - Running <TaskInstance: pyspark_etl_pipeline.gold_ingestion manual__2025-03-19T05:14:09.222928+00:00 [running]> on host 43ddbbc85ca6
[2025-03-19T15:36:43.941+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='caiovos@hotmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pyspark_etl_pipeline' AIRFLOW_CTX_TASK_ID='gold_ingestion' AIRFLOW_CTX_EXECUTION_DATE='2025-03-19T05:14:09.222928+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-19T05:14:09.222928+00:00'
[2025-03-19T15:36:43.944+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-19T15:36:43.964+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-19T15:36:43.965+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'spark-submit --master local /opt/***/dags/gold_ingestion.py']
[2025-03-19T15:36:43.978+0000] {subprocess.py:99} INFO - Output:
[2025-03-19T15:36:48.671+0000] {subprocess.py:106} INFO - 25/03/19 15:36:48 INFO SparkContext: Running Spark version 3.5.5
[2025-03-19T15:36:48.675+0000] {subprocess.py:106} INFO - 25/03/19 15:36:48 INFO SparkContext: OS info Linux, 6.12.5-linuxkit, amd64
[2025-03-19T15:36:48.676+0000] {subprocess.py:106} INFO - 25/03/19 15:36:48 INFO SparkContext: Java version 17.0.14
[2025-03-19T15:36:48.767+0000] {subprocess.py:106} INFO - 25/03/19 15:36:48 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-03-19T15:36:48.934+0000] {subprocess.py:106} INFO - 25/03/19 15:36:48 INFO ResourceUtils: ==============================================================
[2025-03-19T15:36:48.935+0000] {subprocess.py:106} INFO - 25/03/19 15:36:48 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-03-19T15:36:48.937+0000] {subprocess.py:106} INFO - 25/03/19 15:36:48 INFO ResourceUtils: ==============================================================
[2025-03-19T15:36:48.940+0000] {subprocess.py:106} INFO - 25/03/19 15:36:48 INFO SparkContext: Submitted application: GoldLayer
[2025-03-19T15:36:48.982+0000] {subprocess.py:106} INFO - 25/03/19 15:36:48 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-03-19T15:36:48.997+0000] {subprocess.py:106} INFO - 25/03/19 15:36:48 INFO ResourceProfile: Limiting resource is cpu
[2025-03-19T15:36:48.998+0000] {subprocess.py:106} INFO - 25/03/19 15:36:48 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-03-19T15:36:49.087+0000] {subprocess.py:106} INFO - 25/03/19 15:36:49 INFO SecurityManager: Changing view acls to: default
[2025-03-19T15:36:49.087+0000] {subprocess.py:106} INFO - 25/03/19 15:36:49 INFO SecurityManager: Changing modify acls to: default
[2025-03-19T15:36:49.088+0000] {subprocess.py:106} INFO - 25/03/19 15:36:49 INFO SecurityManager: Changing view acls groups to:
[2025-03-19T15:36:49.091+0000] {subprocess.py:106} INFO - 25/03/19 15:36:49 INFO SecurityManager: Changing modify acls groups to:
[2025-03-19T15:36:49.093+0000] {subprocess.py:106} INFO - 25/03/19 15:36:49 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: default; groups with view permissions: EMPTY; users with modify permissions: default; groups with modify permissions: EMPTY
[2025-03-19T15:36:49.554+0000] {subprocess.py:106} INFO - 25/03/19 15:36:49 INFO Utils: Successfully started service 'sparkDriver' on port 35077.
[2025-03-19T15:36:49.606+0000] {subprocess.py:106} INFO - 25/03/19 15:36:49 INFO SparkEnv: Registering MapOutputTracker
[2025-03-19T15:36:49.665+0000] {subprocess.py:106} INFO - 25/03/19 15:36:49 INFO SparkEnv: Registering BlockManagerMaster
[2025-03-19T15:36:49.694+0000] {subprocess.py:106} INFO - 25/03/19 15:36:49 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-03-19T15:36:49.695+0000] {subprocess.py:106} INFO - 25/03/19 15:36:49 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-03-19T15:36:49.702+0000] {subprocess.py:106} INFO - 25/03/19 15:36:49 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-03-19T15:36:49.735+0000] {subprocess.py:106} INFO - 25/03/19 15:36:49 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-aa5b6111-c1d6-43b3-b00e-14636af63991
[2025-03-19T15:36:49.760+0000] {subprocess.py:106} INFO - 25/03/19 15:36:49 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-03-19T15:36:49.785+0000] {subprocess.py:106} INFO - 25/03/19 15:36:49 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-03-19T15:36:49.987+0000] {subprocess.py:106} INFO - 25/03/19 15:36:49 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-03-19T15:36:50.088+0000] {subprocess.py:106} INFO - 25/03/19 15:36:50 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-03-19T15:36:50.295+0000] {subprocess.py:106} INFO - 25/03/19 15:36:50 INFO Executor: Starting executor ID driver on host 43ddbbc85ca6
[2025-03-19T15:36:50.297+0000] {subprocess.py:106} INFO - 25/03/19 15:36:50 INFO Executor: OS info Linux, 6.12.5-linuxkit, amd64
[2025-03-19T15:36:50.298+0000] {subprocess.py:106} INFO - 25/03/19 15:36:50 INFO Executor: Java version 17.0.14
[2025-03-19T15:36:50.308+0000] {subprocess.py:106} INFO - 25/03/19 15:36:50 INFO Executor: Starting executor with user classpath (userClassPathFirst = false): ''
[2025-03-19T15:36:50.310+0000] {subprocess.py:106} INFO - 25/03/19 15:36:50 INFO Executor: Created or updated repl class loader org.apache.spark.util.MutableURLClassLoader@6710369a for default.
[2025-03-19T15:36:50.363+0000] {subprocess.py:106} INFO - 25/03/19 15:36:50 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 35263.
[2025-03-19T15:36:50.363+0000] {subprocess.py:106} INFO - 25/03/19 15:36:50 INFO NettyBlockTransferService: Server created on 43ddbbc85ca6:35263
[2025-03-19T15:36:50.365+0000] {subprocess.py:106} INFO - 25/03/19 15:36:50 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-03-19T15:36:50.373+0000] {subprocess.py:106} INFO - 25/03/19 15:36:50 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 43ddbbc85ca6, 35263, None)
[2025-03-19T15:36:50.379+0000] {subprocess.py:106} INFO - 25/03/19 15:36:50 INFO BlockManagerMasterEndpoint: Registering block manager 43ddbbc85ca6:35263 with 434.4 MiB RAM, BlockManagerId(driver, 43ddbbc85ca6, 35263, None)
[2025-03-19T15:36:50.381+0000] {subprocess.py:106} INFO - 25/03/19 15:36:50 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 43ddbbc85ca6, 35263, None)
[2025-03-19T15:36:50.383+0000] {subprocess.py:106} INFO - 25/03/19 15:36:50 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 43ddbbc85ca6, 35263, None)
[2025-03-19T15:36:51.011+0000] {subprocess.py:106} INFO - 25/03/19 15:36:51 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-03-19T15:36:51.021+0000] {subprocess.py:106} INFO - 25/03/19 15:36:51 INFO SharedState: Warehouse path is 'file:/tmp/***tmput_5h3m9/spark-warehouse'.
[2025-03-19T15:36:52.739+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-03-19T15:36:52.740+0000] {subprocess.py:106} INFO -   File "/opt/***/dags/gold_ingestion.py", line 13, in <module>
[2025-03-19T15:36:52.740+0000] {subprocess.py:106} INFO -     silver_df = spark.read.parquet(silver_path)
[2025-03-19T15:36:52.741+0000] {subprocess.py:106} INFO -                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-03-19T15:36:52.741+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 544, in parquet
[2025-03-19T15:36:52.742+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2025-03-19T15:36:52.743+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 185, in deco
[2025-03-19T15:36:52.752+0000] {subprocess.py:106} INFO - pyspark.errors.exceptions.captured.AnalysisException: [PATH_NOT_FOUND] Path does not exist: file:/tmp/***tmput_5h3m9/medallion_data/silver_layer.
[2025-03-19T15:36:52.833+0000] {subprocess.py:106} INFO - 25/03/19 15:36:52 INFO SparkContext: Invoking stop() from shutdown hook
[2025-03-19T15:36:52.834+0000] {subprocess.py:106} INFO - 25/03/19 15:36:52 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2025-03-19T15:36:52.855+0000] {subprocess.py:106} INFO - 25/03/19 15:36:52 INFO SparkUI: Stopped Spark web UI at http://43ddbbc85ca6:4040
[2025-03-19T15:36:52.874+0000] {subprocess.py:106} INFO - 25/03/19 15:36:52 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-03-19T15:36:52.892+0000] {subprocess.py:106} INFO - 25/03/19 15:36:52 INFO MemoryStore: MemoryStore cleared
[2025-03-19T15:36:52.893+0000] {subprocess.py:106} INFO - 25/03/19 15:36:52 INFO BlockManager: BlockManager stopped
[2025-03-19T15:36:52.900+0000] {subprocess.py:106} INFO - 25/03/19 15:36:52 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-03-19T15:36:52.904+0000] {subprocess.py:106} INFO - 25/03/19 15:36:52 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-03-19T15:36:52.917+0000] {subprocess.py:106} INFO - 25/03/19 15:36:52 INFO SparkContext: Successfully stopped SparkContext
[2025-03-19T15:36:52.918+0000] {subprocess.py:106} INFO - 25/03/19 15:36:52 INFO ShutdownHookManager: Shutdown hook called
[2025-03-19T15:36:52.918+0000] {subprocess.py:106} INFO - 25/03/19 15:36:52 INFO ShutdownHookManager: Deleting directory /tmp/spark-5f995ab8-d70a-44c5-b27b-e2cc07725613
[2025-03-19T15:36:52.925+0000] {subprocess.py:106} INFO - 25/03/19 15:36:52 INFO ShutdownHookManager: Deleting directory /tmp/spark-5f995ab8-d70a-44c5-b27b-e2cc07725613/pyspark-2ab7dcf0-23b7-4510-af6e-64f61c9a0718
[2025-03-19T15:36:52.933+0000] {subprocess.py:106} INFO - 25/03/19 15:36:52 INFO ShutdownHookManager: Deleting directory /tmp/spark-d76f2a0f-7312-4f2e-8683-b7a82c014642
[2025-03-19T15:36:52.970+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-03-19T15:36:52.985+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-19T15:36:52.997+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=pyspark_etl_pipeline, task_id=gold_ingestion, run_id=manual__2025-03-19T05:14:09.222928+00:00, execution_date=20250319T051409, start_date=20250319T153643, end_date=20250319T153652
[2025-03-19T15:36:53.022+0000] {base.py:84} INFO - Retrieving connection 'smtp_default'
[2025-03-19T15:36:53.023+0000] {email.py:272} INFO - Email alerting: attempt 1
[2025-03-19T15:36:55.444+0000] {email.py:283} INFO - Sent an alert email to ['caiovos@hotmail.com']
[2025-03-19T15:36:56.247+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-19T15:36:56.250+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 121 for task gold_ingestion (Bash command failed. The command returned a non-zero exit code 1.; 363)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-19T15:36:56.300+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-19T15:36:56.330+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-19T15:36:56.333+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
