[2025-03-19T16:16:28.458+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-19T16:16:28.534+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pyspark_etl_pipeline.gold_ingestion manual__2025-03-19T05:14:09.222928+00:00 [queued]>
[2025-03-19T16:16:28.581+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pyspark_etl_pipeline.gold_ingestion manual__2025-03-19T05:14:09.222928+00:00 [queued]>
[2025-03-19T16:16:28.582+0000] {taskinstance.py:2867} INFO - Starting attempt 3 of 4
[2025-03-19T16:16:28.640+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): gold_ingestion> on 2025-03-19 05:14:09.222928+00:00
[2025-03-19T16:16:28.666+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pyspark_etl_pipeline', 'gold_ingestion', 'manual__2025-03-19T05:14:09.222928+00:00', '--job-id', '150', '--raw', '--subdir', 'DAGS_FOLDER/dag_pipeline.py', '--cfg-path', '/tmp/tmpsgdlzss9']
[2025-03-19T16:16:28.677+0000] {standard_task_runner.py:105} INFO - Job 150: Subtask gold_ingestion
[2025-03-19T16:16:28.684+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1029) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-19T16:16:28.687+0000] {standard_task_runner.py:72} INFO - Started process 1038 to run task
[2025-03-19T16:16:28.865+0000] {task_command.py:467} INFO - Running <TaskInstance: pyspark_etl_pipeline.gold_ingestion manual__2025-03-19T05:14:09.222928+00:00 [running]> on host 20dc670367b9
[2025-03-19T16:16:29.083+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='caiovos@hotmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pyspark_etl_pipeline' AIRFLOW_CTX_TASK_ID='gold_ingestion' AIRFLOW_CTX_EXECUTION_DATE='2025-03-19T05:14:09.222928+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-19T05:14:09.222928+00:00'
[2025-03-19T16:16:29.091+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-19T16:16:29.132+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-19T16:16:29.134+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'spark-submit --master local /opt/***/dags/gold_ingestion.py']
[2025-03-19T16:16:29.153+0000] {subprocess.py:99} INFO - Output:
[2025-03-19T16:16:34.807+0000] {subprocess.py:106} INFO - 25/03/19 16:16:34 INFO SparkContext: Running Spark version 3.5.5
[2025-03-19T16:16:34.813+0000] {subprocess.py:106} INFO - 25/03/19 16:16:34 INFO SparkContext: OS info Linux, 6.12.5-linuxkit, amd64
[2025-03-19T16:16:34.814+0000] {subprocess.py:106} INFO - 25/03/19 16:16:34 INFO SparkContext: Java version 17.0.14
[2025-03-19T16:16:34.898+0000] {subprocess.py:106} INFO - 25/03/19 16:16:34 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-03-19T16:16:35.034+0000] {subprocess.py:106} INFO - 25/03/19 16:16:35 INFO ResourceUtils: ==============================================================
[2025-03-19T16:16:35.035+0000] {subprocess.py:106} INFO - 25/03/19 16:16:35 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-03-19T16:16:35.036+0000] {subprocess.py:106} INFO - 25/03/19 16:16:35 INFO ResourceUtils: ==============================================================
[2025-03-19T16:16:35.037+0000] {subprocess.py:106} INFO - 25/03/19 16:16:35 INFO SparkContext: Submitted application: GoldLayer
[2025-03-19T16:16:35.085+0000] {subprocess.py:106} INFO - 25/03/19 16:16:35 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-03-19T16:16:35.106+0000] {subprocess.py:106} INFO - 25/03/19 16:16:35 INFO ResourceProfile: Limiting resource is cpu
[2025-03-19T16:16:35.111+0000] {subprocess.py:106} INFO - 25/03/19 16:16:35 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-03-19T16:16:35.202+0000] {subprocess.py:106} INFO - 25/03/19 16:16:35 INFO SecurityManager: Changing view acls to: default
[2025-03-19T16:16:35.204+0000] {subprocess.py:106} INFO - 25/03/19 16:16:35 INFO SecurityManager: Changing modify acls to: default
[2025-03-19T16:16:35.205+0000] {subprocess.py:106} INFO - 25/03/19 16:16:35 INFO SecurityManager: Changing view acls groups to:
[2025-03-19T16:16:35.206+0000] {subprocess.py:106} INFO - 25/03/19 16:16:35 INFO SecurityManager: Changing modify acls groups to:
[2025-03-19T16:16:35.207+0000] {subprocess.py:106} INFO - 25/03/19 16:16:35 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: default; groups with view permissions: EMPTY; users with modify permissions: default; groups with modify permissions: EMPTY
[2025-03-19T16:16:35.654+0000] {subprocess.py:106} INFO - 25/03/19 16:16:35 INFO Utils: Successfully started service 'sparkDriver' on port 43623.
[2025-03-19T16:16:35.749+0000] {subprocess.py:106} INFO - 25/03/19 16:16:35 INFO SparkEnv: Registering MapOutputTracker
[2025-03-19T16:16:35.849+0000] {subprocess.py:106} INFO - 25/03/19 16:16:35 INFO SparkEnv: Registering BlockManagerMaster
[2025-03-19T16:16:35.895+0000] {subprocess.py:106} INFO - 25/03/19 16:16:35 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-03-19T16:16:35.896+0000] {subprocess.py:106} INFO - 25/03/19 16:16:35 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-03-19T16:16:35.903+0000] {subprocess.py:106} INFO - 25/03/19 16:16:35 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-03-19T16:16:35.951+0000] {subprocess.py:106} INFO - 25/03/19 16:16:35 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-fac65954-af30-4ae5-a2e9-3afdd25d8af3
[2025-03-19T16:16:35.979+0000] {subprocess.py:106} INFO - 25/03/19 16:16:35 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-03-19T16:16:36.002+0000] {subprocess.py:106} INFO - 25/03/19 16:16:36 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-03-19T16:16:36.225+0000] {subprocess.py:106} INFO - 25/03/19 16:16:36 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-03-19T16:16:36.372+0000] {subprocess.py:106} INFO - 25/03/19 16:16:36 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-03-19T16:16:36.717+0000] {subprocess.py:106} INFO - 25/03/19 16:16:36 INFO Executor: Starting executor ID driver on host 20dc670367b9
[2025-03-19T16:16:36.719+0000] {subprocess.py:106} INFO - 25/03/19 16:16:36 INFO Executor: OS info Linux, 6.12.5-linuxkit, amd64
[2025-03-19T16:16:36.721+0000] {subprocess.py:106} INFO - 25/03/19 16:16:36 INFO Executor: Java version 17.0.14
[2025-03-19T16:16:36.762+0000] {subprocess.py:106} INFO - 25/03/19 16:16:36 INFO Executor: Starting executor with user classpath (userClassPathFirst = false): ''
[2025-03-19T16:16:36.764+0000] {subprocess.py:106} INFO - 25/03/19 16:16:36 INFO Executor: Created or updated repl class loader org.apache.spark.util.MutableURLClassLoader@6710369a for default.
[2025-03-19T16:16:36.846+0000] {subprocess.py:106} INFO - 25/03/19 16:16:36 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 39069.
[2025-03-19T16:16:36.847+0000] {subprocess.py:106} INFO - 25/03/19 16:16:36 INFO NettyBlockTransferService: Server created on 20dc670367b9:39069
[2025-03-19T16:16:36.854+0000] {subprocess.py:106} INFO - 25/03/19 16:16:36 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-03-19T16:16:36.872+0000] {subprocess.py:106} INFO - 25/03/19 16:16:36 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 20dc670367b9, 39069, None)
[2025-03-19T16:16:36.879+0000] {subprocess.py:106} INFO - 25/03/19 16:16:36 INFO BlockManagerMasterEndpoint: Registering block manager 20dc670367b9:39069 with 434.4 MiB RAM, BlockManagerId(driver, 20dc670367b9, 39069, None)
[2025-03-19T16:16:36.884+0000] {subprocess.py:106} INFO - 25/03/19 16:16:36 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 20dc670367b9, 39069, None)
[2025-03-19T16:16:36.886+0000] {subprocess.py:106} INFO - 25/03/19 16:16:36 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 20dc670367b9, 39069, None)
[2025-03-19T16:16:37.642+0000] {subprocess.py:106} INFO - 25/03/19 16:16:37 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-03-19T16:16:37.652+0000] {subprocess.py:106} INFO - 25/03/19 16:16:37 INFO SharedState: Warehouse path is 'file:/tmp/***tmph4ewpcot/spark-warehouse'.
[2025-03-19T16:16:39.369+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-03-19T16:16:39.370+0000] {subprocess.py:106} INFO -   File "/opt/***/dags/gold_ingestion.py", line 13, in <module>
[2025-03-19T16:16:39.371+0000] {subprocess.py:106} INFO -     silver_df = spark.read.parquet(silver_path)
[2025-03-19T16:16:39.372+0000] {subprocess.py:106} INFO -                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-03-19T16:16:39.372+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 544, in parquet
[2025-03-19T16:16:39.374+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2025-03-19T16:16:39.375+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 185, in deco
[2025-03-19T16:16:39.385+0000] {subprocess.py:106} INFO - pyspark.errors.exceptions.captured.AnalysisException: [PATH_NOT_FOUND] Path does not exist: file:/tmp/***tmph4ewpcot/medallion_data/silver_layer.
[2025-03-19T16:16:39.492+0000] {subprocess.py:106} INFO - 25/03/19 16:16:39 INFO SparkContext: Invoking stop() from shutdown hook
[2025-03-19T16:16:39.493+0000] {subprocess.py:106} INFO - 25/03/19 16:16:39 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2025-03-19T16:16:39.524+0000] {subprocess.py:106} INFO - 25/03/19 16:16:39 INFO SparkUI: Stopped Spark web UI at http://20dc670367b9:4040
[2025-03-19T16:16:39.550+0000] {subprocess.py:106} INFO - 25/03/19 16:16:39 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-03-19T16:16:39.572+0000] {subprocess.py:106} INFO - 25/03/19 16:16:39 INFO MemoryStore: MemoryStore cleared
[2025-03-19T16:16:39.573+0000] {subprocess.py:106} INFO - 25/03/19 16:16:39 INFO BlockManager: BlockManager stopped
[2025-03-19T16:16:39.582+0000] {subprocess.py:106} INFO - 25/03/19 16:16:39 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-03-19T16:16:39.588+0000] {subprocess.py:106} INFO - 25/03/19 16:16:39 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-03-19T16:16:39.599+0000] {subprocess.py:106} INFO - 25/03/19 16:16:39 INFO SparkContext: Successfully stopped SparkContext
[2025-03-19T16:16:39.601+0000] {subprocess.py:106} INFO - 25/03/19 16:16:39 INFO ShutdownHookManager: Shutdown hook called
[2025-03-19T16:16:39.603+0000] {subprocess.py:106} INFO - 25/03/19 16:16:39 INFO ShutdownHookManager: Deleting directory /tmp/spark-10b3db13-eb4f-4ac1-a2be-07e27f835915/pyspark-cadcb00b-b348-4d81-a50e-ad87a9bac404
[2025-03-19T16:16:39.610+0000] {subprocess.py:106} INFO - 25/03/19 16:16:39 INFO ShutdownHookManager: Deleting directory /tmp/spark-10b3db13-eb4f-4ac1-a2be-07e27f835915
[2025-03-19T16:16:39.618+0000] {subprocess.py:106} INFO - 25/03/19 16:16:39 INFO ShutdownHookManager: Deleting directory /tmp/spark-3fa16184-ca58-452b-aea0-be25e6c18827
[2025-03-19T16:16:39.677+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-03-19T16:16:39.696+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-19T16:16:39.711+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=pyspark_etl_pipeline, task_id=gold_ingestion, run_id=manual__2025-03-19T05:14:09.222928+00:00, execution_date=20250319T051409, start_date=20250319T161628, end_date=20250319T161639
[2025-03-19T16:16:39.744+0000] {base.py:84} INFO - Retrieving connection 'smtp_default'
[2025-03-19T16:16:39.744+0000] {email.py:272} INFO - Email alerting: attempt 1
[2025-03-19T16:16:41.194+0000] {email.py:283} INFO - Sent an alert email to ['caiovos@hotmail.com']
[2025-03-19T16:16:42.005+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-19T16:16:42.006+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 150 for task gold_ingestion (Bash command failed. The command returned a non-zero exit code 1.; 1038)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-19T16:16:42.051+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-19T16:16:42.086+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-19T16:16:42.089+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
