[2025-03-19T15:41:25.487+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-19T15:41:25.516+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pyspark_etl_pipeline.gold_ingestion manual__2025-03-19T05:14:09.222928+00:00 [queued]>
[2025-03-19T15:41:25.533+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pyspark_etl_pipeline.gold_ingestion manual__2025-03-19T05:14:09.222928+00:00 [queued]>
[2025-03-19T15:41:25.534+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 3
[2025-03-19T15:41:25.553+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): gold_ingestion> on 2025-03-19 05:14:09.222928+00:00
[2025-03-19T15:41:25.565+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pyspark_etl_pipeline', 'gold_ingestion', 'manual__2025-03-19T05:14:09.222928+00:00', '--job-id', '126', '--raw', '--subdir', 'DAGS_FOLDER/dag_pipeline.py', '--cfg-path', '/tmp/tmp31e1x3_8']
[2025-03-19T15:41:25.569+0000] {standard_task_runner.py:105} INFO - Job 126: Subtask gold_ingestion
[2025-03-19T15:41:25.570+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=491) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-19T15:41:25.571+0000] {standard_task_runner.py:72} INFO - Started process 492 to run task
[2025-03-19T15:41:25.637+0000] {task_command.py:467} INFO - Running <TaskInstance: pyspark_etl_pipeline.gold_ingestion manual__2025-03-19T05:14:09.222928+00:00 [running]> on host 15114d483679
[2025-03-19T15:41:25.767+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='caiovos@hotmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pyspark_etl_pipeline' AIRFLOW_CTX_TASK_ID='gold_ingestion' AIRFLOW_CTX_EXECUTION_DATE='2025-03-19T05:14:09.222928+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-19T05:14:09.222928+00:00'
[2025-03-19T15:41:25.769+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-19T15:41:25.786+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-19T15:41:25.787+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'spark-submit --master local /opt/***/dags/gold_ingestion.py']
[2025-03-19T15:41:25.800+0000] {subprocess.py:99} INFO - Output:
[2025-03-19T15:41:30.042+0000] {subprocess.py:106} INFO - 25/03/19 15:41:30 INFO SparkContext: Running Spark version 3.5.5
[2025-03-19T15:41:30.045+0000] {subprocess.py:106} INFO - 25/03/19 15:41:30 INFO SparkContext: OS info Linux, 6.12.5-linuxkit, amd64
[2025-03-19T15:41:30.046+0000] {subprocess.py:106} INFO - 25/03/19 15:41:30 INFO SparkContext: Java version 17.0.14
[2025-03-19T15:41:30.117+0000] {subprocess.py:106} INFO - 25/03/19 15:41:30 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-03-19T15:41:30.220+0000] {subprocess.py:106} INFO - 25/03/19 15:41:30 INFO ResourceUtils: ==============================================================
[2025-03-19T15:41:30.221+0000] {subprocess.py:106} INFO - 25/03/19 15:41:30 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-03-19T15:41:30.222+0000] {subprocess.py:106} INFO - 25/03/19 15:41:30 INFO ResourceUtils: ==============================================================
[2025-03-19T15:41:30.223+0000] {subprocess.py:106} INFO - 25/03/19 15:41:30 INFO SparkContext: Submitted application: GoldLayer
[2025-03-19T15:41:30.248+0000] {subprocess.py:106} INFO - 25/03/19 15:41:30 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-03-19T15:41:30.259+0000] {subprocess.py:106} INFO - 25/03/19 15:41:30 INFO ResourceProfile: Limiting resource is cpu
[2025-03-19T15:41:30.260+0000] {subprocess.py:106} INFO - 25/03/19 15:41:30 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-03-19T15:41:30.320+0000] {subprocess.py:106} INFO - 25/03/19 15:41:30 INFO SecurityManager: Changing view acls to: default
[2025-03-19T15:41:30.320+0000] {subprocess.py:106} INFO - 25/03/19 15:41:30 INFO SecurityManager: Changing modify acls to: default
[2025-03-19T15:41:30.321+0000] {subprocess.py:106} INFO - 25/03/19 15:41:30 INFO SecurityManager: Changing view acls groups to:
[2025-03-19T15:41:30.322+0000] {subprocess.py:106} INFO - 25/03/19 15:41:30 INFO SecurityManager: Changing modify acls groups to:
[2025-03-19T15:41:30.323+0000] {subprocess.py:106} INFO - 25/03/19 15:41:30 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: default; groups with view permissions: EMPTY; users with modify permissions: default; groups with modify permissions: EMPTY
[2025-03-19T15:41:30.598+0000] {subprocess.py:106} INFO - 25/03/19 15:41:30 INFO Utils: Successfully started service 'sparkDriver' on port 34311.
[2025-03-19T15:41:30.629+0000] {subprocess.py:106} INFO - 25/03/19 15:41:30 INFO SparkEnv: Registering MapOutputTracker
[2025-03-19T15:41:30.673+0000] {subprocess.py:106} INFO - 25/03/19 15:41:30 INFO SparkEnv: Registering BlockManagerMaster
[2025-03-19T15:41:30.698+0000] {subprocess.py:106} INFO - 25/03/19 15:41:30 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-03-19T15:41:30.698+0000] {subprocess.py:106} INFO - 25/03/19 15:41:30 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-03-19T15:41:30.704+0000] {subprocess.py:106} INFO - 25/03/19 15:41:30 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-03-19T15:41:30.728+0000] {subprocess.py:106} INFO - 25/03/19 15:41:30 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-06315957-a534-43c7-8985-614f82bdbb44
[2025-03-19T15:41:30.744+0000] {subprocess.py:106} INFO - 25/03/19 15:41:30 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-03-19T15:41:30.761+0000] {subprocess.py:106} INFO - 25/03/19 15:41:30 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-03-19T15:41:30.915+0000] {subprocess.py:106} INFO - 25/03/19 15:41:30 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-03-19T15:41:31.002+0000] {subprocess.py:106} INFO - 25/03/19 15:41:31 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-03-19T15:41:31.178+0000] {subprocess.py:106} INFO - 25/03/19 15:41:31 INFO Executor: Starting executor ID driver on host 15114d483679
[2025-03-19T15:41:31.178+0000] {subprocess.py:106} INFO - 25/03/19 15:41:31 INFO Executor: OS info Linux, 6.12.5-linuxkit, amd64
[2025-03-19T15:41:31.179+0000] {subprocess.py:106} INFO - 25/03/19 15:41:31 INFO Executor: Java version 17.0.14
[2025-03-19T15:41:31.187+0000] {subprocess.py:106} INFO - 25/03/19 15:41:31 INFO Executor: Starting executor with user classpath (userClassPathFirst = false): ''
[2025-03-19T15:41:31.189+0000] {subprocess.py:106} INFO - 25/03/19 15:41:31 INFO Executor: Created or updated repl class loader org.apache.spark.util.MutableURLClassLoader@6710369a for default.
[2025-03-19T15:41:31.213+0000] {subprocess.py:106} INFO - 25/03/19 15:41:31 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 36061.
[2025-03-19T15:41:31.213+0000] {subprocess.py:106} INFO - 25/03/19 15:41:31 INFO NettyBlockTransferService: Server created on 15114d483679:36061
[2025-03-19T15:41:31.215+0000] {subprocess.py:106} INFO - 25/03/19 15:41:31 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-03-19T15:41:31.222+0000] {subprocess.py:106} INFO - 25/03/19 15:41:31 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 15114d483679, 36061, None)
[2025-03-19T15:41:31.227+0000] {subprocess.py:106} INFO - 25/03/19 15:41:31 INFO BlockManagerMasterEndpoint: Registering block manager 15114d483679:36061 with 434.4 MiB RAM, BlockManagerId(driver, 15114d483679, 36061, None)
[2025-03-19T15:41:31.230+0000] {subprocess.py:106} INFO - 25/03/19 15:41:31 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 15114d483679, 36061, None)
[2025-03-19T15:41:31.231+0000] {subprocess.py:106} INFO - 25/03/19 15:41:31 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 15114d483679, 36061, None)
[2025-03-19T15:41:31.892+0000] {subprocess.py:106} INFO - 25/03/19 15:41:31 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-03-19T15:41:31.906+0000] {subprocess.py:106} INFO - 25/03/19 15:41:31 INFO SharedState: Warehouse path is 'file:/tmp/***tmpk55op7a6/spark-warehouse'.
[2025-03-19T15:41:33.474+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-03-19T15:41:33.475+0000] {subprocess.py:106} INFO -   File "/opt/***/dags/gold_ingestion.py", line 13, in <module>
[2025-03-19T15:41:33.476+0000] {subprocess.py:106} INFO -     silver_df = spark.read.parquet(silver_path)
[2025-03-19T15:41:33.477+0000] {subprocess.py:106} INFO -                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-03-19T15:41:33.477+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 544, in parquet
[2025-03-19T15:41:33.478+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2025-03-19T15:41:33.478+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 185, in deco
[2025-03-19T15:41:33.487+0000] {subprocess.py:106} INFO - pyspark.errors.exceptions.captured.AnalysisException: [PATH_NOT_FOUND] Path does not exist: file:/tmp/***tmpk55op7a6/medallion_data/silver_layer.
[2025-03-19T15:41:33.566+0000] {subprocess.py:106} INFO - 25/03/19 15:41:33 INFO SparkContext: Invoking stop() from shutdown hook
[2025-03-19T15:41:33.567+0000] {subprocess.py:106} INFO - 25/03/19 15:41:33 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2025-03-19T15:41:33.584+0000] {subprocess.py:106} INFO - 25/03/19 15:41:33 INFO SparkUI: Stopped Spark web UI at http://15114d483679:4040
[2025-03-19T15:41:33.601+0000] {subprocess.py:106} INFO - 25/03/19 15:41:33 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-03-19T15:41:33.617+0000] {subprocess.py:106} INFO - 25/03/19 15:41:33 INFO MemoryStore: MemoryStore cleared
[2025-03-19T15:41:33.617+0000] {subprocess.py:106} INFO - 25/03/19 15:41:33 INFO BlockManager: BlockManager stopped
[2025-03-19T15:41:33.624+0000] {subprocess.py:106} INFO - 25/03/19 15:41:33 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-03-19T15:41:33.627+0000] {subprocess.py:106} INFO - 25/03/19 15:41:33 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-03-19T15:41:33.636+0000] {subprocess.py:106} INFO - 25/03/19 15:41:33 INFO SparkContext: Successfully stopped SparkContext
[2025-03-19T15:41:33.637+0000] {subprocess.py:106} INFO - 25/03/19 15:41:33 INFO ShutdownHookManager: Shutdown hook called
[2025-03-19T15:41:33.637+0000] {subprocess.py:106} INFO - 25/03/19 15:41:33 INFO ShutdownHookManager: Deleting directory /tmp/spark-dfebe23f-462c-46e5-bc43-f50f9590c876
[2025-03-19T15:41:33.644+0000] {subprocess.py:106} INFO - 25/03/19 15:41:33 INFO ShutdownHookManager: Deleting directory /tmp/spark-5d8758a2-02f8-4d7f-9af1-d83ee92bf9ec
[2025-03-19T15:41:33.651+0000] {subprocess.py:106} INFO - 25/03/19 15:41:33 INFO ShutdownHookManager: Deleting directory /tmp/spark-5d8758a2-02f8-4d7f-9af1-d83ee92bf9ec/pyspark-1f38bf06-68c5-4de0-927f-9013ecfc9c2f
[2025-03-19T15:41:33.685+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-03-19T15:41:33.701+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-19T15:41:33.713+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=pyspark_etl_pipeline, task_id=gold_ingestion, run_id=manual__2025-03-19T05:14:09.222928+00:00, execution_date=20250319T051409, start_date=20250319T154125, end_date=20250319T154133
[2025-03-19T15:41:33.740+0000] {base.py:84} INFO - Retrieving connection 'smtp_default'
[2025-03-19T15:41:33.741+0000] {email.py:272} INFO - Email alerting: attempt 1
[2025-03-19T15:41:35.150+0000] {email.py:283} INFO - Sent an alert email to ['caiovos@hotmail.com']
[2025-03-19T15:41:35.990+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-19T15:41:35.991+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 126 for task gold_ingestion (Bash command failed. The command returned a non-zero exit code 1.; 492)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-19T15:41:36.007+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-19T15:41:36.049+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-19T15:41:36.052+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
