[2025-03-19T14:22:14.198+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-19T14:22:14.229+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pyspark_etl_pipeline.silver_ingestion manual__2025-03-19T05:14:09.222928+00:00 [queued]>
[2025-03-19T14:22:14.243+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pyspark_etl_pipeline.silver_ingestion manual__2025-03-19T05:14:09.222928+00:00 [queued]>
[2025-03-19T14:22:14.244+0000] {taskinstance.py:2867} INFO - Starting attempt 2 of 2
[2025-03-19T14:22:14.268+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): silver_ingestion> on 2025-03-19 05:14:09.222928+00:00
[2025-03-19T14:22:14.279+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pyspark_etl_pipeline', 'silver_ingestion', 'manual__2025-03-19T05:14:09.222928+00:00', '--job-id', '101', '--raw', '--subdir', 'DAGS_FOLDER/dag_pipeline.py', '--cfg-path', '/tmp/tmpewxhls9g']
[2025-03-19T14:22:14.283+0000] {standard_task_runner.py:105} INFO - Job 101: Subtask silver_ingestion
[2025-03-19T14:22:14.285+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=6190) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-19T14:22:14.286+0000] {standard_task_runner.py:72} INFO - Started process 6191 to run task
[2025-03-19T14:22:14.359+0000] {task_command.py:467} INFO - Running <TaskInstance: pyspark_etl_pipeline.silver_ingestion manual__2025-03-19T05:14:09.222928+00:00 [running]> on host 691ef0d21155
[2025-03-19T14:22:14.494+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='caiovos@hotmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pyspark_etl_pipeline' AIRFLOW_CTX_TASK_ID='silver_ingestion' AIRFLOW_CTX_EXECUTION_DATE='2025-03-19T05:14:09.222928+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-19T05:14:09.222928+00:00'
[2025-03-19T14:22:14.495+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-19T14:22:14.517+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-19T14:22:14.522+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'spark-submit --master local /opt/***/dags/silver_ingestion.py']
[2025-03-19T14:22:14.534+0000] {subprocess.py:99} INFO - Output:
[2025-03-19T14:22:18.841+0000] {subprocess.py:106} INFO - 25/03/19 14:22:18 INFO SparkContext: Running Spark version 3.5.5
[2025-03-19T14:22:18.845+0000] {subprocess.py:106} INFO - 25/03/19 14:22:18 INFO SparkContext: OS info Linux, 6.12.5-linuxkit, amd64
[2025-03-19T14:22:18.846+0000] {subprocess.py:106} INFO - 25/03/19 14:22:18 INFO SparkContext: Java version 17.0.14
[2025-03-19T14:22:18.930+0000] {subprocess.py:106} INFO - 25/03/19 14:22:18 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-03-19T14:22:19.045+0000] {subprocess.py:106} INFO - 25/03/19 14:22:19 INFO ResourceUtils: ==============================================================
[2025-03-19T14:22:19.045+0000] {subprocess.py:106} INFO - 25/03/19 14:22:19 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-03-19T14:22:19.046+0000] {subprocess.py:106} INFO - 25/03/19 14:22:19 INFO ResourceUtils: ==============================================================
[2025-03-19T14:22:19.047+0000] {subprocess.py:106} INFO - 25/03/19 14:22:19 INFO SparkContext: Submitted application: SilverLayer
[2025-03-19T14:22:19.071+0000] {subprocess.py:106} INFO - 25/03/19 14:22:19 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-03-19T14:22:19.081+0000] {subprocess.py:106} INFO - 25/03/19 14:22:19 INFO ResourceProfile: Limiting resource is cpu
[2025-03-19T14:22:19.082+0000] {subprocess.py:106} INFO - 25/03/19 14:22:19 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-03-19T14:22:19.151+0000] {subprocess.py:106} INFO - 25/03/19 14:22:19 INFO SecurityManager: Changing view acls to: default
[2025-03-19T14:22:19.152+0000] {subprocess.py:106} INFO - 25/03/19 14:22:19 INFO SecurityManager: Changing modify acls to: default
[2025-03-19T14:22:19.153+0000] {subprocess.py:106} INFO - 25/03/19 14:22:19 INFO SecurityManager: Changing view acls groups to:
[2025-03-19T14:22:19.154+0000] {subprocess.py:106} INFO - 25/03/19 14:22:19 INFO SecurityManager: Changing modify acls groups to:
[2025-03-19T14:22:19.155+0000] {subprocess.py:106} INFO - 25/03/19 14:22:19 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: default; groups with view permissions: EMPTY; users with modify permissions: default; groups with modify permissions: EMPTY
[2025-03-19T14:22:19.547+0000] {subprocess.py:106} INFO - 25/03/19 14:22:19 INFO Utils: Successfully started service 'sparkDriver' on port 43205.
[2025-03-19T14:22:19.590+0000] {subprocess.py:106} INFO - 25/03/19 14:22:19 INFO SparkEnv: Registering MapOutputTracker
[2025-03-19T14:22:19.633+0000] {subprocess.py:106} INFO - 25/03/19 14:22:19 INFO SparkEnv: Registering BlockManagerMaster
[2025-03-19T14:22:19.661+0000] {subprocess.py:106} INFO - 25/03/19 14:22:19 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-03-19T14:22:19.663+0000] {subprocess.py:106} INFO - 25/03/19 14:22:19 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-03-19T14:22:19.669+0000] {subprocess.py:106} INFO - 25/03/19 14:22:19 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-03-19T14:22:19.716+0000] {subprocess.py:106} INFO - 25/03/19 14:22:19 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-c6170ce7-3fc2-432a-9cfe-3c707a2ec243
[2025-03-19T14:22:19.745+0000] {subprocess.py:106} INFO - 25/03/19 14:22:19 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-03-19T14:22:19.779+0000] {subprocess.py:106} INFO - 25/03/19 14:22:19 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-03-19T14:22:19.958+0000] {subprocess.py:106} INFO - 25/03/19 14:22:19 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-03-19T14:22:20.042+0000] {subprocess.py:106} INFO - 25/03/19 14:22:20 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-03-19T14:22:20.191+0000] {subprocess.py:106} INFO - 25/03/19 14:22:20 INFO Executor: Starting executor ID driver on host 691ef0d21155
[2025-03-19T14:22:20.191+0000] {subprocess.py:106} INFO - 25/03/19 14:22:20 INFO Executor: OS info Linux, 6.12.5-linuxkit, amd64
[2025-03-19T14:22:20.192+0000] {subprocess.py:106} INFO - 25/03/19 14:22:20 INFO Executor: Java version 17.0.14
[2025-03-19T14:22:20.200+0000] {subprocess.py:106} INFO - 25/03/19 14:22:20 INFO Executor: Starting executor with user classpath (userClassPathFirst = false): ''
[2025-03-19T14:22:20.202+0000] {subprocess.py:106} INFO - 25/03/19 14:22:20 INFO Executor: Created or updated repl class loader org.apache.spark.util.MutableURLClassLoader@16829667 for default.
[2025-03-19T14:22:20.231+0000] {subprocess.py:106} INFO - 25/03/19 14:22:20 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 46361.
[2025-03-19T14:22:20.232+0000] {subprocess.py:106} INFO - 25/03/19 14:22:20 INFO NettyBlockTransferService: Server created on 691ef0d21155:46361
[2025-03-19T14:22:20.233+0000] {subprocess.py:106} INFO - 25/03/19 14:22:20 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-03-19T14:22:20.240+0000] {subprocess.py:106} INFO - 25/03/19 14:22:20 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 691ef0d21155, 46361, None)
[2025-03-19T14:22:20.245+0000] {subprocess.py:106} INFO - 25/03/19 14:22:20 INFO BlockManagerMasterEndpoint: Registering block manager 691ef0d21155:46361 with 434.4 MiB RAM, BlockManagerId(driver, 691ef0d21155, 46361, None)
[2025-03-19T14:22:20.247+0000] {subprocess.py:106} INFO - 25/03/19 14:22:20 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 691ef0d21155, 46361, None)
[2025-03-19T14:22:20.249+0000] {subprocess.py:106} INFO - 25/03/19 14:22:20 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 691ef0d21155, 46361, None)
[2025-03-19T14:22:20.874+0000] {subprocess.py:106} INFO - 25/03/19 14:22:20 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-03-19T14:22:20.883+0000] {subprocess.py:106} INFO - 25/03/19 14:22:20 INFO SharedState: Warehouse path is 'file:/tmp/***tmpzln2ta6q/spark-warehouse'.
[2025-03-19T14:22:22.702+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-03-19T14:22:22.703+0000] {subprocess.py:106} INFO -   File "/opt/***/dags/silver_ingestion.py", line 13, in <module>
[2025-03-19T14:22:22.704+0000] {subprocess.py:106} INFO -     df = spark.read.option("multiline", "true").json(bronze_path)
[2025-03-19T14:22:22.705+0000] {subprocess.py:106} INFO -          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-03-19T14:22:22.706+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 425, in json
[2025-03-19T14:22:22.708+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2025-03-19T14:22:22.709+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 185, in deco
[2025-03-19T14:22:22.725+0000] {subprocess.py:106} INFO - pyspark.errors.exceptions.captured.AnalysisException: [PATH_NOT_FOUND] Path does not exist: file:/tmp/***tmpzln2ta6q/medallion_data/bronze_layer.json.
[2025-03-19T14:22:22.804+0000] {subprocess.py:106} INFO - 25/03/19 14:22:22 INFO SparkContext: Invoking stop() from shutdown hook
[2025-03-19T14:22:22.805+0000] {subprocess.py:106} INFO - 25/03/19 14:22:22 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2025-03-19T14:22:22.845+0000] {subprocess.py:106} INFO - 25/03/19 14:22:22 INFO SparkUI: Stopped Spark web UI at http://691ef0d21155:4040
[2025-03-19T14:22:22.884+0000] {subprocess.py:106} INFO - 25/03/19 14:22:22 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-03-19T14:22:22.914+0000] {subprocess.py:106} INFO - 25/03/19 14:22:22 INFO MemoryStore: MemoryStore cleared
[2025-03-19T14:22:22.915+0000] {subprocess.py:106} INFO - 25/03/19 14:22:22 INFO BlockManager: BlockManager stopped
[2025-03-19T14:22:22.925+0000] {subprocess.py:106} INFO - 25/03/19 14:22:22 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-03-19T14:22:22.931+0000] {subprocess.py:106} INFO - 25/03/19 14:22:22 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-03-19T14:22:22.948+0000] {subprocess.py:106} INFO - 25/03/19 14:22:22 INFO SparkContext: Successfully stopped SparkContext
[2025-03-19T14:22:22.949+0000] {subprocess.py:106} INFO - 25/03/19 14:22:22 INFO ShutdownHookManager: Shutdown hook called
[2025-03-19T14:22:22.950+0000] {subprocess.py:106} INFO - 25/03/19 14:22:22 INFO ShutdownHookManager: Deleting directory /tmp/spark-f2e589c1-acc8-41c9-aa96-f162b0e715b9
[2025-03-19T14:22:22.964+0000] {subprocess.py:106} INFO - 25/03/19 14:22:22 INFO ShutdownHookManager: Deleting directory /tmp/spark-e63a3027-b116-422c-9d90-cb41e4351890
[2025-03-19T14:22:22.974+0000] {subprocess.py:106} INFO - 25/03/19 14:22:22 INFO ShutdownHookManager: Deleting directory /tmp/spark-e63a3027-b116-422c-9d90-cb41e4351890/pyspark-ed0b8d69-c13f-4485-b7c7-be30d4e97ede
[2025-03-19T14:22:23.018+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-03-19T14:22:23.033+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-19T14:22:23.041+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=pyspark_etl_pipeline, task_id=silver_ingestion, run_id=manual__2025-03-19T05:14:09.222928+00:00, execution_date=20250319T051409, start_date=20250319T142214, end_date=20250319T142223
[2025-03-19T14:22:23.066+0000] {base.py:84} INFO - Retrieving connection 'smtp_default'
[2025-03-19T14:22:23.067+0000] {email.py:272} INFO - Email alerting: attempt 1
[2025-03-19T14:22:24.375+0000] {email.py:283} INFO - Sent an alert email to ['caiovos@hotmail.com']
[2025-03-19T14:22:25.085+0000] {taskinstance.py:1564} INFO - Executing callback at index 0: notify_failure
[2025-03-19T14:22:25.095+0000] {base.py:84} INFO - Retrieving connection 'smtp_default'
[2025-03-19T14:22:25.096+0000] {email.py:272} INFO - Email alerting: attempt 1
[2025-03-19T14:22:26.242+0000] {email.py:283} INFO - Sent an alert email to ['cvsalimoliveira@gmail.com']
[2025-03-19T14:22:27.032+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-19T14:22:27.033+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 101 for task silver_ingestion (Bash command failed. The command returned a non-zero exit code 1.; 6191)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-19T14:22:27.049+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-19T14:22:27.081+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-19T14:22:27.087+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
