[2025-03-19T15:26:04.701+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-19T15:26:04.733+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pyspark_etl_pipeline.silver_ingestion manual__2025-03-19T05:14:09.222928+00:00 [queued]>
[2025-03-19T15:26:04.753+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pyspark_etl_pipeline.silver_ingestion manual__2025-03-19T05:14:09.222928+00:00 [queued]>
[2025-03-19T15:26:04.754+0000] {taskinstance.py:2867} INFO - Starting attempt 6 of 6
[2025-03-19T15:26:04.773+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): silver_ingestion> on 2025-03-19 05:14:09.222928+00:00
[2025-03-19T15:26:04.783+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pyspark_etl_pipeline', 'silver_ingestion', 'manual__2025-03-19T05:14:09.222928+00:00', '--job-id', '117', '--raw', '--subdir', 'DAGS_FOLDER/dag_pipeline.py', '--cfg-path', '/tmp/tmpfgtlqb0_']
[2025-03-19T15:26:04.786+0000] {standard_task_runner.py:105} INFO - Job 117: Subtask silver_ingestion
[2025-03-19T15:26:04.788+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=693) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-19T15:26:04.789+0000] {standard_task_runner.py:72} INFO - Started process 694 to run task
[2025-03-19T15:26:04.854+0000] {task_command.py:467} INFO - Running <TaskInstance: pyspark_etl_pipeline.silver_ingestion manual__2025-03-19T05:14:09.222928+00:00 [running]> on host f2ee2d018606
[2025-03-19T15:26:04.972+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='caiovos@hotmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pyspark_etl_pipeline' AIRFLOW_CTX_TASK_ID='silver_ingestion' AIRFLOW_CTX_EXECUTION_DATE='2025-03-19T05:14:09.222928+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-19T05:14:09.222928+00:00'
[2025-03-19T15:26:04.974+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-19T15:26:04.995+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-19T15:26:04.996+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'spark-submit --master local /opt/***/dags/silver_ingestion.py']
[2025-03-19T15:26:05.006+0000] {subprocess.py:99} INFO - Output:
[2025-03-19T15:26:09.776+0000] {subprocess.py:106} INFO - 25/03/19 15:26:09 INFO SparkContext: Running Spark version 3.5.5
[2025-03-19T15:26:09.779+0000] {subprocess.py:106} INFO - 25/03/19 15:26:09 INFO SparkContext: OS info Linux, 6.12.5-linuxkit, amd64
[2025-03-19T15:26:09.780+0000] {subprocess.py:106} INFO - 25/03/19 15:26:09 INFO SparkContext: Java version 17.0.14
[2025-03-19T15:26:09.884+0000] {subprocess.py:106} INFO - 25/03/19 15:26:09 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-03-19T15:26:10.051+0000] {subprocess.py:106} INFO - 25/03/19 15:26:10 INFO ResourceUtils: ==============================================================
[2025-03-19T15:26:10.052+0000] {subprocess.py:106} INFO - 25/03/19 15:26:10 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-03-19T15:26:10.052+0000] {subprocess.py:106} INFO - 25/03/19 15:26:10 INFO ResourceUtils: ==============================================================
[2025-03-19T15:26:10.053+0000] {subprocess.py:106} INFO - 25/03/19 15:26:10 INFO SparkContext: Submitted application: SilverLayer
[2025-03-19T15:26:10.082+0000] {subprocess.py:106} INFO - 25/03/19 15:26:10 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-03-19T15:26:10.094+0000] {subprocess.py:106} INFO - 25/03/19 15:26:10 INFO ResourceProfile: Limiting resource is cpu
[2025-03-19T15:26:10.097+0000] {subprocess.py:106} INFO - 25/03/19 15:26:10 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-03-19T15:26:10.208+0000] {subprocess.py:106} INFO - 25/03/19 15:26:10 INFO SecurityManager: Changing view acls to: default
[2025-03-19T15:26:10.211+0000] {subprocess.py:106} INFO - 25/03/19 15:26:10 INFO SecurityManager: Changing modify acls to: default
[2025-03-19T15:26:10.211+0000] {subprocess.py:106} INFO - 25/03/19 15:26:10 INFO SecurityManager: Changing view acls groups to:
[2025-03-19T15:26:10.213+0000] {subprocess.py:106} INFO - 25/03/19 15:26:10 INFO SecurityManager: Changing modify acls groups to:
[2025-03-19T15:26:10.214+0000] {subprocess.py:106} INFO - 25/03/19 15:26:10 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: default; groups with view permissions: EMPTY; users with modify permissions: default; groups with modify permissions: EMPTY
[2025-03-19T15:26:10.622+0000] {subprocess.py:106} INFO - 25/03/19 15:26:10 INFO Utils: Successfully started service 'sparkDriver' on port 42233.
[2025-03-19T15:26:10.657+0000] {subprocess.py:106} INFO - 25/03/19 15:26:10 INFO SparkEnv: Registering MapOutputTracker
[2025-03-19T15:26:10.717+0000] {subprocess.py:106} INFO - 25/03/19 15:26:10 INFO SparkEnv: Registering BlockManagerMaster
[2025-03-19T15:26:10.746+0000] {subprocess.py:106} INFO - 25/03/19 15:26:10 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-03-19T15:26:10.748+0000] {subprocess.py:106} INFO - 25/03/19 15:26:10 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-03-19T15:26:10.754+0000] {subprocess.py:106} INFO - 25/03/19 15:26:10 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-03-19T15:26:10.781+0000] {subprocess.py:106} INFO - 25/03/19 15:26:10 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-a00410c2-29bc-4e36-8573-0e729d97d9c6
[2025-03-19T15:26:10.799+0000] {subprocess.py:106} INFO - 25/03/19 15:26:10 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-03-19T15:26:10.820+0000] {subprocess.py:106} INFO - 25/03/19 15:26:10 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-03-19T15:26:11.007+0000] {subprocess.py:106} INFO - 25/03/19 15:26:11 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-03-19T15:26:11.095+0000] {subprocess.py:106} INFO - 25/03/19 15:26:11 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-03-19T15:26:11.286+0000] {subprocess.py:106} INFO - 25/03/19 15:26:11 INFO Executor: Starting executor ID driver on host f2ee2d018606
[2025-03-19T15:26:11.287+0000] {subprocess.py:106} INFO - 25/03/19 15:26:11 INFO Executor: OS info Linux, 6.12.5-linuxkit, amd64
[2025-03-19T15:26:11.288+0000] {subprocess.py:106} INFO - 25/03/19 15:26:11 INFO Executor: Java version 17.0.14
[2025-03-19T15:26:11.304+0000] {subprocess.py:106} INFO - 25/03/19 15:26:11 INFO Executor: Starting executor with user classpath (userClassPathFirst = false): ''
[2025-03-19T15:26:11.305+0000] {subprocess.py:106} INFO - 25/03/19 15:26:11 INFO Executor: Created or updated repl class loader org.apache.spark.util.MutableURLClassLoader@21b2ae6a for default.
[2025-03-19T15:26:11.341+0000] {subprocess.py:106} INFO - 25/03/19 15:26:11 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 37463.
[2025-03-19T15:26:11.341+0000] {subprocess.py:106} INFO - 25/03/19 15:26:11 INFO NettyBlockTransferService: Server created on f2ee2d018606:37463
[2025-03-19T15:26:11.345+0000] {subprocess.py:106} INFO - 25/03/19 15:26:11 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-03-19T15:26:11.354+0000] {subprocess.py:106} INFO - 25/03/19 15:26:11 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, f2ee2d018606, 37463, None)
[2025-03-19T15:26:11.363+0000] {subprocess.py:106} INFO - 25/03/19 15:26:11 INFO BlockManagerMasterEndpoint: Registering block manager f2ee2d018606:37463 with 434.4 MiB RAM, BlockManagerId(driver, f2ee2d018606, 37463, None)
[2025-03-19T15:26:11.370+0000] {subprocess.py:106} INFO - 25/03/19 15:26:11 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, f2ee2d018606, 37463, None)
[2025-03-19T15:26:11.374+0000] {subprocess.py:106} INFO - 25/03/19 15:26:11 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, f2ee2d018606, 37463, None)
[2025-03-19T15:26:12.419+0000] {subprocess.py:106} INFO - 25/03/19 15:26:12 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-03-19T15:26:12.434+0000] {subprocess.py:106} INFO - 25/03/19 15:26:12 INFO SharedState: Warehouse path is 'file:/tmp/***tmpag9cduck/spark-warehouse'.
[2025-03-19T15:26:14.497+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-03-19T15:26:14.498+0000] {subprocess.py:106} INFO -   File "/opt/***/dags/silver_ingestion.py", line 11, in <module>
[2025-03-19T15:26:14.499+0000] {subprocess.py:106} INFO -     df = spark.read.option("multiline", "true").json(bronze_path)
[2025-03-19T15:26:14.499+0000] {subprocess.py:106} INFO -          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-03-19T15:26:14.500+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 425, in json
[2025-03-19T15:26:14.501+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2025-03-19T15:26:14.502+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 185, in deco
[2025-03-19T15:26:14.515+0000] {subprocess.py:106} INFO - pyspark.errors.exceptions.captured.AnalysisException: [PATH_NOT_FOUND] Path does not exist: file:/tmp/***tmpag9cduck/medallion_data/bronze_layer.json.
[2025-03-19T15:26:14.606+0000] {subprocess.py:106} INFO - 25/03/19 15:26:14 INFO SparkContext: Invoking stop() from shutdown hook
[2025-03-19T15:26:14.607+0000] {subprocess.py:106} INFO - 25/03/19 15:26:14 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2025-03-19T15:26:14.624+0000] {subprocess.py:106} INFO - 25/03/19 15:26:14 INFO SparkUI: Stopped Spark web UI at http://f2ee2d018606:4040
[2025-03-19T15:26:14.649+0000] {subprocess.py:106} INFO - 25/03/19 15:26:14 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-03-19T15:26:14.667+0000] {subprocess.py:106} INFO - 25/03/19 15:26:14 INFO MemoryStore: MemoryStore cleared
[2025-03-19T15:26:14.668+0000] {subprocess.py:106} INFO - 25/03/19 15:26:14 INFO BlockManager: BlockManager stopped
[2025-03-19T15:26:14.675+0000] {subprocess.py:106} INFO - 25/03/19 15:26:14 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-03-19T15:26:14.681+0000] {subprocess.py:106} INFO - 25/03/19 15:26:14 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-03-19T15:26:14.693+0000] {subprocess.py:106} INFO - 25/03/19 15:26:14 INFO SparkContext: Successfully stopped SparkContext
[2025-03-19T15:26:14.694+0000] {subprocess.py:106} INFO - 25/03/19 15:26:14 INFO ShutdownHookManager: Shutdown hook called
[2025-03-19T15:26:14.695+0000] {subprocess.py:106} INFO - 25/03/19 15:26:14 INFO ShutdownHookManager: Deleting directory /tmp/spark-6967b5c5-03b1-4c00-8527-5cce2dbf73b2
[2025-03-19T15:26:14.704+0000] {subprocess.py:106} INFO - 25/03/19 15:26:14 INFO ShutdownHookManager: Deleting directory /tmp/spark-32e0f226-d64e-4845-8d5e-4914328252ce
[2025-03-19T15:26:14.714+0000] {subprocess.py:106} INFO - 25/03/19 15:26:14 INFO ShutdownHookManager: Deleting directory /tmp/spark-32e0f226-d64e-4845-8d5e-4914328252ce/pyspark-95e9d923-e1e9-4a06-9b5d-32bfba930708
[2025-03-19T15:26:14.769+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-03-19T15:26:14.794+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-19T15:26:14.800+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=pyspark_etl_pipeline, task_id=silver_ingestion, run_id=manual__2025-03-19T05:14:09.222928+00:00, execution_date=20250319T051409, start_date=20250319T152604, end_date=20250319T152614
[2025-03-19T15:26:14.827+0000] {base.py:84} INFO - Retrieving connection 'smtp_default'
[2025-03-19T15:26:14.828+0000] {email.py:272} INFO - Email alerting: attempt 1
[2025-03-19T15:26:17.114+0000] {email.py:283} INFO - Sent an alert email to ['caiovos@hotmail.com']
[2025-03-19T15:26:17.888+0000] {taskinstance.py:1564} INFO - Executing callback at index 0: notify_failure
[2025-03-19T15:26:17.900+0000] {base.py:84} INFO - Retrieving connection 'smtp_default'
[2025-03-19T15:26:17.901+0000] {email.py:272} INFO - Email alerting: attempt 1
[2025-03-19T15:26:19.128+0000] {email.py:283} INFO - Sent an alert email to ['cvsalimoliveira@gmail.com']
[2025-03-19T15:26:19.914+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-19T15:26:19.915+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 117 for task silver_ingestion (Bash command failed. The command returned a non-zero exit code 1.; 694)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-19T15:26:19.949+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-19T15:26:19.986+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-19T15:26:19.992+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
