[2025-03-19T15:06:20.120+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-19T15:06:20.171+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pyspark_etl_pipeline.silver_ingestion manual__2025-03-19T05:14:09.222928+00:00 [queued]>
[2025-03-19T15:06:20.188+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pyspark_etl_pipeline.silver_ingestion manual__2025-03-19T05:14:09.222928+00:00 [queued]>
[2025-03-19T15:06:20.189+0000] {taskinstance.py:2867} INFO - Starting attempt 4 of 4
[2025-03-19T15:06:20.209+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): silver_ingestion> on 2025-03-19 05:14:09.222928+00:00
[2025-03-19T15:06:20.218+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pyspark_etl_pipeline', 'silver_ingestion', 'manual__2025-03-19T05:14:09.222928+00:00', '--job-id', '112', '--raw', '--subdir', 'DAGS_FOLDER/dag_pipeline.py', '--cfg-path', '/tmp/tmp3mxt3xdh']
[2025-03-19T15:06:20.223+0000] {standard_task_runner.py:105} INFO - Job 112: Subtask silver_ingestion
[2025-03-19T15:06:20.223+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=727) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-19T15:06:20.226+0000] {standard_task_runner.py:72} INFO - Started process 728 to run task
[2025-03-19T15:06:20.291+0000] {task_command.py:467} INFO - Running <TaskInstance: pyspark_etl_pipeline.silver_ingestion manual__2025-03-19T05:14:09.222928+00:00 [running]> on host ef5eed66b5b5
[2025-03-19T15:06:20.420+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='caiovos@hotmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pyspark_etl_pipeline' AIRFLOW_CTX_TASK_ID='silver_ingestion' AIRFLOW_CTX_EXECUTION_DATE='2025-03-19T05:14:09.222928+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-19T05:14:09.222928+00:00'
[2025-03-19T15:06:20.421+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-19T15:06:20.443+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-19T15:06:20.446+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'spark-submit --master local /opt/***/dags/silver_ingestion.py']
[2025-03-19T15:06:20.465+0000] {subprocess.py:99} INFO - Output:
[2025-03-19T15:06:24.519+0000] {subprocess.py:106} INFO - 25/03/19 15:06:24 INFO SparkContext: Running Spark version 3.5.5
[2025-03-19T15:06:24.522+0000] {subprocess.py:106} INFO - 25/03/19 15:06:24 INFO SparkContext: OS info Linux, 6.12.5-linuxkit, amd64
[2025-03-19T15:06:24.523+0000] {subprocess.py:106} INFO - 25/03/19 15:06:24 INFO SparkContext: Java version 17.0.14
[2025-03-19T15:06:24.582+0000] {subprocess.py:106} INFO - 25/03/19 15:06:24 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-03-19T15:06:24.679+0000] {subprocess.py:106} INFO - 25/03/19 15:06:24 INFO ResourceUtils: ==============================================================
[2025-03-19T15:06:24.680+0000] {subprocess.py:106} INFO - 25/03/19 15:06:24 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-03-19T15:06:24.681+0000] {subprocess.py:106} INFO - 25/03/19 15:06:24 INFO ResourceUtils: ==============================================================
[2025-03-19T15:06:24.682+0000] {subprocess.py:106} INFO - 25/03/19 15:06:24 INFO SparkContext: Submitted application: SilverLayer
[2025-03-19T15:06:24.702+0000] {subprocess.py:106} INFO - 25/03/19 15:06:24 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-03-19T15:06:24.712+0000] {subprocess.py:106} INFO - 25/03/19 15:06:24 INFO ResourceProfile: Limiting resource is cpu
[2025-03-19T15:06:24.713+0000] {subprocess.py:106} INFO - 25/03/19 15:06:24 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-03-19T15:06:24.771+0000] {subprocess.py:106} INFO - 25/03/19 15:06:24 INFO SecurityManager: Changing view acls to: default
[2025-03-19T15:06:24.772+0000] {subprocess.py:106} INFO - 25/03/19 15:06:24 INFO SecurityManager: Changing modify acls to: default
[2025-03-19T15:06:24.774+0000] {subprocess.py:106} INFO - 25/03/19 15:06:24 INFO SecurityManager: Changing view acls groups to:
[2025-03-19T15:06:24.775+0000] {subprocess.py:106} INFO - 25/03/19 15:06:24 INFO SecurityManager: Changing modify acls groups to:
[2025-03-19T15:06:24.776+0000] {subprocess.py:106} INFO - 25/03/19 15:06:24 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: default; groups with view permissions: EMPTY; users with modify permissions: default; groups with modify permissions: EMPTY
[2025-03-19T15:06:25.146+0000] {subprocess.py:106} INFO - 25/03/19 15:06:25 INFO Utils: Successfully started service 'sparkDriver' on port 34771.
[2025-03-19T15:06:25.176+0000] {subprocess.py:106} INFO - 25/03/19 15:06:25 INFO SparkEnv: Registering MapOutputTracker
[2025-03-19T15:06:25.211+0000] {subprocess.py:106} INFO - 25/03/19 15:06:25 INFO SparkEnv: Registering BlockManagerMaster
[2025-03-19T15:06:25.235+0000] {subprocess.py:106} INFO - 25/03/19 15:06:25 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-03-19T15:06:25.235+0000] {subprocess.py:106} INFO - 25/03/19 15:06:25 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-03-19T15:06:25.240+0000] {subprocess.py:106} INFO - 25/03/19 15:06:25 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-03-19T15:06:25.265+0000] {subprocess.py:106} INFO - 25/03/19 15:06:25 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-59288813-2c55-48ac-a81d-6e7c6ea02b5d
[2025-03-19T15:06:25.282+0000] {subprocess.py:106} INFO - 25/03/19 15:06:25 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-03-19T15:06:25.301+0000] {subprocess.py:106} INFO - 25/03/19 15:06:25 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-03-19T15:06:25.486+0000] {subprocess.py:106} INFO - 25/03/19 15:06:25 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-03-19T15:06:25.578+0000] {subprocess.py:106} INFO - 25/03/19 15:06:25 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-03-19T15:06:25.775+0000] {subprocess.py:106} INFO - 25/03/19 15:06:25 INFO Executor: Starting executor ID driver on host ef5eed66b5b5
[2025-03-19T15:06:25.779+0000] {subprocess.py:106} INFO - 25/03/19 15:06:25 INFO Executor: OS info Linux, 6.12.5-linuxkit, amd64
[2025-03-19T15:06:25.781+0000] {subprocess.py:106} INFO - 25/03/19 15:06:25 INFO Executor: Java version 17.0.14
[2025-03-19T15:06:25.787+0000] {subprocess.py:106} INFO - 25/03/19 15:06:25 INFO Executor: Starting executor with user classpath (userClassPathFirst = false): ''
[2025-03-19T15:06:25.788+0000] {subprocess.py:106} INFO - 25/03/19 15:06:25 INFO Executor: Created or updated repl class loader org.apache.spark.util.MutableURLClassLoader@5123949a for default.
[2025-03-19T15:06:25.824+0000] {subprocess.py:106} INFO - 25/03/19 15:06:25 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 39245.
[2025-03-19T15:06:25.825+0000] {subprocess.py:106} INFO - 25/03/19 15:06:25 INFO NettyBlockTransferService: Server created on ef5eed66b5b5:39245
[2025-03-19T15:06:25.828+0000] {subprocess.py:106} INFO - 25/03/19 15:06:25 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-03-19T15:06:25.837+0000] {subprocess.py:106} INFO - 25/03/19 15:06:25 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, ef5eed66b5b5, 39245, None)
[2025-03-19T15:06:25.841+0000] {subprocess.py:106} INFO - 25/03/19 15:06:25 INFO BlockManagerMasterEndpoint: Registering block manager ef5eed66b5b5:39245 with 434.4 MiB RAM, BlockManagerId(driver, ef5eed66b5b5, 39245, None)
[2025-03-19T15:06:25.844+0000] {subprocess.py:106} INFO - 25/03/19 15:06:25 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, ef5eed66b5b5, 39245, None)
[2025-03-19T15:06:25.845+0000] {subprocess.py:106} INFO - 25/03/19 15:06:25 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, ef5eed66b5b5, 39245, None)
[2025-03-19T15:06:26.410+0000] {subprocess.py:106} INFO - 25/03/19 15:06:26 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-03-19T15:06:26.418+0000] {subprocess.py:106} INFO - 25/03/19 15:06:26 INFO SharedState: Warehouse path is 'file:/tmp/***tmpcfdgr_sq/spark-warehouse'.
[2025-03-19T15:06:27.800+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-03-19T15:06:27.801+0000] {subprocess.py:106} INFO -   File "/opt/***/dags/silver_ingestion.py", line 11, in <module>
[2025-03-19T15:06:27.802+0000] {subprocess.py:106} INFO -     df = spark.read.option("multiline", "true").json(bronze_path)
[2025-03-19T15:06:27.802+0000] {subprocess.py:106} INFO -          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-03-19T15:06:27.802+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 425, in json
[2025-03-19T15:06:27.803+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2025-03-19T15:06:27.803+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 185, in deco
[2025-03-19T15:06:27.810+0000] {subprocess.py:106} INFO - pyspark.errors.exceptions.captured.AnalysisException: [PATH_NOT_FOUND] Path does not exist: file:/tmp/***tmpcfdgr_sq/medallion_data/bronze_layer.json.
[2025-03-19T15:06:27.863+0000] {subprocess.py:106} INFO - 25/03/19 15:06:27 INFO SparkContext: Invoking stop() from shutdown hook
[2025-03-19T15:06:27.863+0000] {subprocess.py:106} INFO - 25/03/19 15:06:27 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2025-03-19T15:06:27.878+0000] {subprocess.py:106} INFO - 25/03/19 15:06:27 INFO SparkUI: Stopped Spark web UI at http://ef5eed66b5b5:4040
[2025-03-19T15:06:27.893+0000] {subprocess.py:106} INFO - 25/03/19 15:06:27 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-03-19T15:06:27.910+0000] {subprocess.py:106} INFO - 25/03/19 15:06:27 INFO MemoryStore: MemoryStore cleared
[2025-03-19T15:06:27.911+0000] {subprocess.py:106} INFO - 25/03/19 15:06:27 INFO BlockManager: BlockManager stopped
[2025-03-19T15:06:27.922+0000] {subprocess.py:106} INFO - 25/03/19 15:06:27 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-03-19T15:06:27.925+0000] {subprocess.py:106} INFO - 25/03/19 15:06:27 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-03-19T15:06:27.938+0000] {subprocess.py:106} INFO - 25/03/19 15:06:27 INFO SparkContext: Successfully stopped SparkContext
[2025-03-19T15:06:27.939+0000] {subprocess.py:106} INFO - 25/03/19 15:06:27 INFO ShutdownHookManager: Shutdown hook called
[2025-03-19T15:06:27.940+0000] {subprocess.py:106} INFO - 25/03/19 15:06:27 INFO ShutdownHookManager: Deleting directory /tmp/spark-6c0a8ab4-39af-4419-b485-c5fe95f2990e/pyspark-bd79b1cc-83a5-470c-9001-09dce463737e
[2025-03-19T15:06:27.948+0000] {subprocess.py:106} INFO - 25/03/19 15:06:27 INFO ShutdownHookManager: Deleting directory /tmp/spark-6c0a8ab4-39af-4419-b485-c5fe95f2990e
[2025-03-19T15:06:27.957+0000] {subprocess.py:106} INFO - 25/03/19 15:06:27 INFO ShutdownHookManager: Deleting directory /tmp/spark-fe74401f-d990-44c6-a1d3-d8a05eae86b5
[2025-03-19T15:06:28.013+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-03-19T15:06:28.027+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-19T15:06:28.034+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=pyspark_etl_pipeline, task_id=silver_ingestion, run_id=manual__2025-03-19T05:14:09.222928+00:00, execution_date=20250319T051409, start_date=20250319T150620, end_date=20250319T150628
[2025-03-19T15:06:28.058+0000] {base.py:84} INFO - Retrieving connection 'smtp_default'
[2025-03-19T15:06:28.061+0000] {email.py:272} INFO - Email alerting: attempt 1
[2025-03-19T15:06:29.492+0000] {email.py:283} INFO - Sent an alert email to ['caiovos@hotmail.com']
[2025-03-19T15:06:30.273+0000] {taskinstance.py:1564} INFO - Executing callback at index 0: notify_failure
[2025-03-19T15:06:30.285+0000] {base.py:84} INFO - Retrieving connection 'smtp_default'
[2025-03-19T15:06:30.286+0000] {email.py:272} INFO - Email alerting: attempt 1
[2025-03-19T15:06:31.506+0000] {email.py:283} INFO - Sent an alert email to ['cvsalimoliveira@gmail.com']
[2025-03-19T15:06:32.299+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-19T15:06:32.299+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 112 for task silver_ingestion (Bash command failed. The command returned a non-zero exit code 1.; 728)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-19T15:06:32.348+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-19T15:06:32.386+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-19T15:06:32.397+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
