[2025-03-19T15:20:53.542+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-19T15:20:53.613+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pyspark_etl_pipeline.silver_ingestion manual__2025-03-19T05:14:09.222928+00:00 [queued]>
[2025-03-19T15:20:53.628+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pyspark_etl_pipeline.silver_ingestion manual__2025-03-19T05:14:09.222928+00:00 [queued]>
[2025-03-19T15:20:53.628+0000] {taskinstance.py:2867} INFO - Starting attempt 5 of 6
[2025-03-19T15:20:53.640+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): silver_ingestion> on 2025-03-19 05:14:09.222928+00:00
[2025-03-19T15:20:53.647+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pyspark_etl_pipeline', 'silver_ingestion', 'manual__2025-03-19T05:14:09.222928+00:00', '--job-id', '116', '--raw', '--subdir', 'DAGS_FOLDER/dag_pipeline.py', '--cfg-path', '/tmp/tmprisgt_lp']
[2025-03-19T15:20:53.661+0000] {standard_task_runner.py:105} INFO - Job 116: Subtask silver_ingestion
[2025-03-19T15:20:53.652+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=447) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-19T15:20:53.666+0000] {standard_task_runner.py:72} INFO - Started process 448 to run task
[2025-03-19T15:20:54.541+0000] {task_command.py:467} INFO - Running <TaskInstance: pyspark_etl_pipeline.silver_ingestion manual__2025-03-19T05:14:09.222928+00:00 [running]> on host f2ee2d018606
[2025-03-19T15:20:55.287+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='caiovos@hotmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pyspark_etl_pipeline' AIRFLOW_CTX_TASK_ID='silver_ingestion' AIRFLOW_CTX_EXECUTION_DATE='2025-03-19T05:14:09.222928+00:00' AIRFLOW_CTX_TRY_NUMBER='5' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-19T05:14:09.222928+00:00'
[2025-03-19T15:20:55.290+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-19T15:20:55.350+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-19T15:20:55.355+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'spark-submit --master local /opt/***/dags/silver_ingestion.py']
[2025-03-19T15:20:55.399+0000] {subprocess.py:99} INFO - Output:
[2025-03-19T15:21:00.288+0000] {subprocess.py:106} INFO - 25/03/19 15:21:00 INFO SparkContext: Running Spark version 3.5.5
[2025-03-19T15:21:00.310+0000] {subprocess.py:106} INFO - 25/03/19 15:21:00 INFO SparkContext: OS info Linux, 6.12.5-linuxkit, amd64
[2025-03-19T15:21:00.311+0000] {subprocess.py:106} INFO - 25/03/19 15:21:00 INFO SparkContext: Java version 17.0.14
[2025-03-19T15:21:00.378+0000] {subprocess.py:106} INFO - 25/03/19 15:21:00 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-03-19T15:21:00.536+0000] {subprocess.py:106} INFO - 25/03/19 15:21:00 INFO ResourceUtils: ==============================================================
[2025-03-19T15:21:00.549+0000] {subprocess.py:106} INFO - 25/03/19 15:21:00 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-03-19T15:21:00.550+0000] {subprocess.py:106} INFO - 25/03/19 15:21:00 INFO ResourceUtils: ==============================================================
[2025-03-19T15:21:00.550+0000] {subprocess.py:106} INFO - 25/03/19 15:21:00 INFO SparkContext: Submitted application: SilverLayer
[2025-03-19T15:21:00.566+0000] {subprocess.py:106} INFO - 25/03/19 15:21:00 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-03-19T15:21:00.585+0000] {subprocess.py:106} INFO - 25/03/19 15:21:00 INFO ResourceProfile: Limiting resource is cpu
[2025-03-19T15:21:00.586+0000] {subprocess.py:106} INFO - 25/03/19 15:21:00 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-03-19T15:21:00.667+0000] {subprocess.py:106} INFO - 25/03/19 15:21:00 INFO SecurityManager: Changing view acls to: default
[2025-03-19T15:21:00.669+0000] {subprocess.py:106} INFO - 25/03/19 15:21:00 INFO SecurityManager: Changing modify acls to: default
[2025-03-19T15:21:00.670+0000] {subprocess.py:106} INFO - 25/03/19 15:21:00 INFO SecurityManager: Changing view acls groups to:
[2025-03-19T15:21:00.672+0000] {subprocess.py:106} INFO - 25/03/19 15:21:00 INFO SecurityManager: Changing modify acls groups to:
[2025-03-19T15:21:00.675+0000] {subprocess.py:106} INFO - 25/03/19 15:21:00 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: default; groups with view permissions: EMPTY; users with modify permissions: default; groups with modify permissions: EMPTY
[2025-03-19T15:21:01.132+0000] {subprocess.py:106} INFO - 25/03/19 15:21:01 INFO Utils: Successfully started service 'sparkDriver' on port 44341.
[2025-03-19T15:21:01.180+0000] {subprocess.py:106} INFO - 25/03/19 15:21:01 INFO SparkEnv: Registering MapOutputTracker
[2025-03-19T15:21:01.219+0000] {subprocess.py:106} INFO - 25/03/19 15:21:01 INFO SparkEnv: Registering BlockManagerMaster
[2025-03-19T15:21:01.242+0000] {subprocess.py:106} INFO - 25/03/19 15:21:01 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-03-19T15:21:01.243+0000] {subprocess.py:106} INFO - 25/03/19 15:21:01 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-03-19T15:21:01.250+0000] {subprocess.py:106} INFO - 25/03/19 15:21:01 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-03-19T15:21:01.284+0000] {subprocess.py:106} INFO - 25/03/19 15:21:01 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-d6cc657c-cfcb-4629-9b73-c3744f09f348
[2025-03-19T15:21:01.306+0000] {subprocess.py:106} INFO - 25/03/19 15:21:01 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-03-19T15:21:01.339+0000] {subprocess.py:106} INFO - 25/03/19 15:21:01 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-03-19T15:21:01.480+0000] {subprocess.py:106} INFO - 25/03/19 15:21:01 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-03-19T15:21:01.559+0000] {subprocess.py:106} INFO - 25/03/19 15:21:01 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-03-19T15:21:01.684+0000] {subprocess.py:106} INFO - 25/03/19 15:21:01 INFO Executor: Starting executor ID driver on host f2ee2d018606
[2025-03-19T15:21:01.685+0000] {subprocess.py:106} INFO - 25/03/19 15:21:01 INFO Executor: OS info Linux, 6.12.5-linuxkit, amd64
[2025-03-19T15:21:01.686+0000] {subprocess.py:106} INFO - 25/03/19 15:21:01 INFO Executor: Java version 17.0.14
[2025-03-19T15:21:01.694+0000] {subprocess.py:106} INFO - 25/03/19 15:21:01 INFO Executor: Starting executor with user classpath (userClassPathFirst = false): ''
[2025-03-19T15:21:01.695+0000] {subprocess.py:106} INFO - 25/03/19 15:21:01 INFO Executor: Created or updated repl class loader org.apache.spark.util.MutableURLClassLoader@14430c86 for default.
[2025-03-19T15:21:01.720+0000] {subprocess.py:106} INFO - 25/03/19 15:21:01 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 45609.
[2025-03-19T15:21:01.720+0000] {subprocess.py:106} INFO - 25/03/19 15:21:01 INFO NettyBlockTransferService: Server created on f2ee2d018606:45609
[2025-03-19T15:21:01.722+0000] {subprocess.py:106} INFO - 25/03/19 15:21:01 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-03-19T15:21:01.729+0000] {subprocess.py:106} INFO - 25/03/19 15:21:01 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, f2ee2d018606, 45609, None)
[2025-03-19T15:21:01.733+0000] {subprocess.py:106} INFO - 25/03/19 15:21:01 INFO BlockManagerMasterEndpoint: Registering block manager f2ee2d018606:45609 with 434.4 MiB RAM, BlockManagerId(driver, f2ee2d018606, 45609, None)
[2025-03-19T15:21:01.736+0000] {subprocess.py:106} INFO - 25/03/19 15:21:01 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, f2ee2d018606, 45609, None)
[2025-03-19T15:21:01.737+0000] {subprocess.py:106} INFO - 25/03/19 15:21:01 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, f2ee2d018606, 45609, None)
[2025-03-19T15:21:02.249+0000] {subprocess.py:106} INFO - 25/03/19 15:21:02 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-03-19T15:21:02.258+0000] {subprocess.py:106} INFO - 25/03/19 15:21:02 INFO SharedState: Warehouse path is 'file:/tmp/***tmp_xia8f2_/spark-warehouse'.
[2025-03-19T15:21:03.617+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-03-19T15:21:03.618+0000] {subprocess.py:106} INFO -   File "/opt/***/dags/silver_ingestion.py", line 11, in <module>
[2025-03-19T15:21:03.619+0000] {subprocess.py:106} INFO -     df = spark.read.option("multiline", "true").json(bronze_path)
[2025-03-19T15:21:03.620+0000] {subprocess.py:106} INFO -          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-03-19T15:21:03.621+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 425, in json
[2025-03-19T15:21:03.622+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2025-03-19T15:21:03.624+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 185, in deco
[2025-03-19T15:21:03.639+0000] {subprocess.py:106} INFO - pyspark.errors.exceptions.captured.AnalysisException: [PATH_NOT_FOUND] Path does not exist: file:/tmp/***tmp_xia8f2_/medallion_data/bronze_layer.json.
[2025-03-19T15:21:03.727+0000] {subprocess.py:106} INFO - 25/03/19 15:21:03 INFO SparkContext: Invoking stop() from shutdown hook
[2025-03-19T15:21:03.728+0000] {subprocess.py:106} INFO - 25/03/19 15:21:03 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2025-03-19T15:21:03.747+0000] {subprocess.py:106} INFO - 25/03/19 15:21:03 INFO SparkUI: Stopped Spark web UI at http://f2ee2d018606:4040
[2025-03-19T15:21:03.781+0000] {subprocess.py:106} INFO - 25/03/19 15:21:03 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-03-19T15:21:03.809+0000] {subprocess.py:106} INFO - 25/03/19 15:21:03 INFO MemoryStore: MemoryStore cleared
[2025-03-19T15:21:03.810+0000] {subprocess.py:106} INFO - 25/03/19 15:21:03 INFO BlockManager: BlockManager stopped
[2025-03-19T15:21:03.820+0000] {subprocess.py:106} INFO - 25/03/19 15:21:03 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-03-19T15:21:03.828+0000] {subprocess.py:106} INFO - 25/03/19 15:21:03 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-03-19T15:21:03.840+0000] {subprocess.py:106} INFO - 25/03/19 15:21:03 INFO SparkContext: Successfully stopped SparkContext
[2025-03-19T15:21:03.842+0000] {subprocess.py:106} INFO - 25/03/19 15:21:03 INFO ShutdownHookManager: Shutdown hook called
[2025-03-19T15:21:03.843+0000] {subprocess.py:106} INFO - 25/03/19 15:21:03 INFO ShutdownHookManager: Deleting directory /tmp/spark-f9d72891-bfe5-48d9-b4b5-386d6805fe17
[2025-03-19T15:21:03.852+0000] {subprocess.py:106} INFO - 25/03/19 15:21:03 INFO ShutdownHookManager: Deleting directory /tmp/spark-5527d749-94a9-4cca-a6c8-cb692e11907b/pyspark-ad0705ae-7fae-4d2a-8ab2-b95224dfdfc0
[2025-03-19T15:21:03.864+0000] {subprocess.py:106} INFO - 25/03/19 15:21:03 INFO ShutdownHookManager: Deleting directory /tmp/spark-5527d749-94a9-4cca-a6c8-cb692e11907b
[2025-03-19T15:21:03.924+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-03-19T15:21:03.950+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-19T15:21:03.969+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=pyspark_etl_pipeline, task_id=silver_ingestion, run_id=manual__2025-03-19T05:14:09.222928+00:00, execution_date=20250319T051409, start_date=20250319T152053, end_date=20250319T152103
[2025-03-19T15:21:04.004+0000] {base.py:84} INFO - Retrieving connection 'smtp_default'
[2025-03-19T15:21:04.005+0000] {email.py:272} INFO - Email alerting: attempt 1
[2025-03-19T15:21:05.361+0000] {email.py:283} INFO - Sent an alert email to ['caiovos@hotmail.com']
[2025-03-19T15:21:06.557+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-19T15:21:06.558+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 116 for task silver_ingestion (Bash command failed. The command returned a non-zero exit code 1.; 448)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-19T15:21:06.607+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-19T15:21:06.633+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-19T15:21:06.635+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
