[2025-03-19T15:54:15.874+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-19T15:54:15.903+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pyspark_etl_pipeline.silver_ingestion manual__2025-03-19T05:14:09.222928+00:00 [queued]>
[2025-03-19T15:54:15.919+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pyspark_etl_pipeline.silver_ingestion manual__2025-03-19T05:14:09.222928+00:00 [queued]>
[2025-03-19T15:54:15.920+0000] {taskinstance.py:2867} INFO - Starting attempt 12 of 12
[2025-03-19T15:54:15.937+0000] {taskinstance.py:2890} INFO - Executing <Task(BashOperator): silver_ingestion> on 2025-03-19 05:14:09.222928+00:00
[2025-03-19T15:54:15.947+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pyspark_etl_pipeline', 'silver_ingestion', 'manual__2025-03-19T05:14:09.222928+00:00', '--job-id', '136', '--raw', '--subdir', 'DAGS_FOLDER/dag_pipeline.py', '--cfg-path', '/tmp/tmpq1z8m6ku']
[2025-03-19T15:54:15.950+0000] {standard_task_runner.py:105} INFO - Job 136: Subtask silver_ingestion
[2025-03-19T15:54:15.952+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=752) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-19T15:54:15.953+0000] {standard_task_runner.py:72} INFO - Started process 753 to run task
[2025-03-19T15:54:16.015+0000] {task_command.py:467} INFO - Running <TaskInstance: pyspark_etl_pipeline.silver_ingestion manual__2025-03-19T05:14:09.222928+00:00 [running]> on host 40696cdf9f68
[2025-03-19T15:54:16.130+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='caiovos@hotmail.com' AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pyspark_etl_pipeline' AIRFLOW_CTX_TASK_ID='silver_ingestion' AIRFLOW_CTX_EXECUTION_DATE='2025-03-19T05:14:09.222928+00:00' AIRFLOW_CTX_TRY_NUMBER='12' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-19T05:14:09.222928+00:00'
[2025-03-19T15:54:16.131+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-19T15:54:16.151+0000] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-03-19T15:54:16.152+0000] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'spark-submit --master local /opt/***/dags/silver_ingestion.py']
[2025-03-19T15:54:16.163+0000] {subprocess.py:99} INFO - Output:
[2025-03-19T15:54:19.596+0000] {subprocess.py:106} INFO - 25/03/19 15:54:19 INFO SparkContext: Running Spark version 3.5.5
[2025-03-19T15:54:19.598+0000] {subprocess.py:106} INFO - 25/03/19 15:54:19 INFO SparkContext: OS info Linux, 6.12.5-linuxkit, amd64
[2025-03-19T15:54:19.599+0000] {subprocess.py:106} INFO - 25/03/19 15:54:19 INFO SparkContext: Java version 17.0.14
[2025-03-19T15:54:19.657+0000] {subprocess.py:106} INFO - 25/03/19 15:54:19 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-03-19T15:54:19.748+0000] {subprocess.py:106} INFO - 25/03/19 15:54:19 INFO ResourceUtils: ==============================================================
[2025-03-19T15:54:19.749+0000] {subprocess.py:106} INFO - 25/03/19 15:54:19 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-03-19T15:54:19.749+0000] {subprocess.py:106} INFO - 25/03/19 15:54:19 INFO ResourceUtils: ==============================================================
[2025-03-19T15:54:19.750+0000] {subprocess.py:106} INFO - 25/03/19 15:54:19 INFO SparkContext: Submitted application: SilverLayer
[2025-03-19T15:54:19.771+0000] {subprocess.py:106} INFO - 25/03/19 15:54:19 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(cores -> name: cores, amount: 1, script: , vendor: , memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-03-19T15:54:19.783+0000] {subprocess.py:106} INFO - 25/03/19 15:54:19 INFO ResourceProfile: Limiting resource is cpu
[2025-03-19T15:54:19.784+0000] {subprocess.py:106} INFO - 25/03/19 15:54:19 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-03-19T15:54:19.836+0000] {subprocess.py:106} INFO - 25/03/19 15:54:19 INFO SecurityManager: Changing view acls to: default
[2025-03-19T15:54:19.837+0000] {subprocess.py:106} INFO - 25/03/19 15:54:19 INFO SecurityManager: Changing modify acls to: default
[2025-03-19T15:54:19.838+0000] {subprocess.py:106} INFO - 25/03/19 15:54:19 INFO SecurityManager: Changing view acls groups to:
[2025-03-19T15:54:19.838+0000] {subprocess.py:106} INFO - 25/03/19 15:54:19 INFO SecurityManager: Changing modify acls groups to:
[2025-03-19T15:54:19.839+0000] {subprocess.py:106} INFO - 25/03/19 15:54:19 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: default; groups with view permissions: EMPTY; users with modify permissions: default; groups with modify permissions: EMPTY
[2025-03-19T15:54:20.081+0000] {subprocess.py:106} INFO - 25/03/19 15:54:20 INFO Utils: Successfully started service 'sparkDriver' on port 36685.
[2025-03-19T15:54:20.112+0000] {subprocess.py:106} INFO - 25/03/19 15:54:20 INFO SparkEnv: Registering MapOutputTracker
[2025-03-19T15:54:20.152+0000] {subprocess.py:106} INFO - 25/03/19 15:54:20 INFO SparkEnv: Registering BlockManagerMaster
[2025-03-19T15:54:20.172+0000] {subprocess.py:106} INFO - 25/03/19 15:54:20 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-03-19T15:54:20.173+0000] {subprocess.py:106} INFO - 25/03/19 15:54:20 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-03-19T15:54:20.179+0000] {subprocess.py:106} INFO - 25/03/19 15:54:20 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-03-19T15:54:20.201+0000] {subprocess.py:106} INFO - 25/03/19 15:54:20 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-8480d961-bb4d-4368-90a7-16526272518a
[2025-03-19T15:54:20.216+0000] {subprocess.py:106} INFO - 25/03/19 15:54:20 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-03-19T15:54:20.231+0000] {subprocess.py:106} INFO - 25/03/19 15:54:20 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-03-19T15:54:20.364+0000] {subprocess.py:106} INFO - 25/03/19 15:54:20 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-03-19T15:54:20.433+0000] {subprocess.py:106} INFO - 25/03/19 15:54:20 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-03-19T15:54:20.606+0000] {subprocess.py:106} INFO - 25/03/19 15:54:20 INFO Executor: Starting executor ID driver on host 40696cdf9f68
[2025-03-19T15:54:20.607+0000] {subprocess.py:106} INFO - 25/03/19 15:54:20 INFO Executor: OS info Linux, 6.12.5-linuxkit, amd64
[2025-03-19T15:54:20.608+0000] {subprocess.py:106} INFO - 25/03/19 15:54:20 INFO Executor: Java version 17.0.14
[2025-03-19T15:54:20.615+0000] {subprocess.py:106} INFO - 25/03/19 15:54:20 INFO Executor: Starting executor with user classpath (userClassPathFirst = false): ''
[2025-03-19T15:54:20.616+0000] {subprocess.py:106} INFO - 25/03/19 15:54:20 INFO Executor: Created or updated repl class loader org.apache.spark.util.MutableURLClassLoader@6710369a for default.
[2025-03-19T15:54:20.637+0000] {subprocess.py:106} INFO - 25/03/19 15:54:20 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 41911.
[2025-03-19T15:54:20.638+0000] {subprocess.py:106} INFO - 25/03/19 15:54:20 INFO NettyBlockTransferService: Server created on 40696cdf9f68:41911
[2025-03-19T15:54:20.639+0000] {subprocess.py:106} INFO - 25/03/19 15:54:20 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-03-19T15:54:20.646+0000] {subprocess.py:106} INFO - 25/03/19 15:54:20 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 40696cdf9f68, 41911, None)
[2025-03-19T15:54:20.649+0000] {subprocess.py:106} INFO - 25/03/19 15:54:20 INFO BlockManagerMasterEndpoint: Registering block manager 40696cdf9f68:41911 with 434.4 MiB RAM, BlockManagerId(driver, 40696cdf9f68, 41911, None)
[2025-03-19T15:54:20.651+0000] {subprocess.py:106} INFO - 25/03/19 15:54:20 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 40696cdf9f68, 41911, None)
[2025-03-19T15:54:20.652+0000] {subprocess.py:106} INFO - 25/03/19 15:54:20 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 40696cdf9f68, 41911, None)
[2025-03-19T15:54:21.164+0000] {subprocess.py:106} INFO - 25/03/19 15:54:21 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-03-19T15:54:21.172+0000] {subprocess.py:106} INFO - 25/03/19 15:54:21 INFO SharedState: Warehouse path is 'file:/tmp/***tmphpx0x9dq/spark-warehouse'.
[2025-03-19T15:54:22.416+0000] {subprocess.py:106} INFO - Traceback (most recent call last):
[2025-03-19T15:54:22.416+0000] {subprocess.py:106} INFO -   File "/opt/***/dags/silver_ingestion.py", line 11, in <module>
[2025-03-19T15:54:22.417+0000] {subprocess.py:106} INFO -     df = spark.read.option("multiline", "true").json(bronze_path)
[2025-03-19T15:54:22.417+0000] {subprocess.py:106} INFO -          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-03-19T15:54:22.418+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 425, in json
[2025-03-19T15:54:22.418+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2025-03-19T15:54:22.419+0000] {subprocess.py:106} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pyspark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 185, in deco
[2025-03-19T15:54:22.427+0000] {subprocess.py:106} INFO - pyspark.errors.exceptions.captured.AnalysisException: [PATH_NOT_FOUND] Path does not exist: file:/tmp/***tmphpx0x9dq/medallion_data/bronze_layer.json.
[2025-03-19T15:54:22.485+0000] {subprocess.py:106} INFO - 25/03/19 15:54:22 INFO SparkContext: Invoking stop() from shutdown hook
[2025-03-19T15:54:22.486+0000] {subprocess.py:106} INFO - 25/03/19 15:54:22 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2025-03-19T15:54:22.501+0000] {subprocess.py:106} INFO - 25/03/19 15:54:22 INFO SparkUI: Stopped Spark web UI at http://40696cdf9f68:4040
[2025-03-19T15:54:22.514+0000] {subprocess.py:106} INFO - 25/03/19 15:54:22 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-03-19T15:54:22.527+0000] {subprocess.py:106} INFO - 25/03/19 15:54:22 INFO MemoryStore: MemoryStore cleared
[2025-03-19T15:54:22.529+0000] {subprocess.py:106} INFO - 25/03/19 15:54:22 INFO BlockManager: BlockManager stopped
[2025-03-19T15:54:22.534+0000] {subprocess.py:106} INFO - 25/03/19 15:54:22 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-03-19T15:54:22.537+0000] {subprocess.py:106} INFO - 25/03/19 15:54:22 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-03-19T15:54:22.546+0000] {subprocess.py:106} INFO - 25/03/19 15:54:22 INFO SparkContext: Successfully stopped SparkContext
[2025-03-19T15:54:22.546+0000] {subprocess.py:106} INFO - 25/03/19 15:54:22 INFO ShutdownHookManager: Shutdown hook called
[2025-03-19T15:54:22.547+0000] {subprocess.py:106} INFO - 25/03/19 15:54:22 INFO ShutdownHookManager: Deleting directory /tmp/spark-75db363b-bec8-4182-ab94-b1e5611ece90
[2025-03-19T15:54:22.555+0000] {subprocess.py:106} INFO - 25/03/19 15:54:22 INFO ShutdownHookManager: Deleting directory /tmp/spark-37a5dfa9-85df-4779-9058-3ae59483933d
[2025-03-19T15:54:22.566+0000] {subprocess.py:106} INFO - 25/03/19 15:54:22 INFO ShutdownHookManager: Deleting directory /tmp/spark-37a5dfa9-85df-4779-9058-3ae59483933d/pyspark-be08cd1a-1199-40c6-a782-bdd119df8b43
[2025-03-19T15:54:22.600+0000] {subprocess.py:110} INFO - Command exited with return code 1
[2025-03-19T15:54:22.614+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-19T15:54:22.620+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=pyspark_etl_pipeline, task_id=silver_ingestion, run_id=manual__2025-03-19T05:14:09.222928+00:00, execution_date=20250319T051409, start_date=20250319T155415, end_date=20250319T155422
[2025-03-19T15:54:22.642+0000] {base.py:84} INFO - Retrieving connection 'smtp_default'
[2025-03-19T15:54:22.643+0000] {email.py:272} INFO - Email alerting: attempt 1
[2025-03-19T15:54:23.966+0000] {email.py:283} INFO - Sent an alert email to ['caiovos@hotmail.com']
[2025-03-19T15:54:24.751+0000] {taskinstance.py:1564} INFO - Executing callback at index 0: notify_failure
[2025-03-19T15:54:24.761+0000] {base.py:84} INFO - Retrieving connection 'smtp_default'
[2025-03-19T15:54:24.763+0000] {email.py:272} INFO - Email alerting: attempt 1
[2025-03-19T15:54:25.979+0000] {email.py:283} INFO - Sent an alert email to ['cvsalimoliveira@gmail.com']
[2025-03-19T15:54:26.756+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-19T15:54:26.757+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 136 for task silver_ingestion (Bash command failed. The command returned a non-zero exit code 1.; 753)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-03-19T15:54:26.769+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-19T15:54:26.779+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
